# Generated by Django 5.1.7 on 2025-05-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backendapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datebase',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='datebase',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='datebase',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
