# Generated by Django 5.1.7 on 2025-05-20 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backendapp', '0002_alter_datebase_email_alter_datebase_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datebase',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
