# Generated by Django 5.1.7 on 2025-10-29 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backendapp', '0003_alter_datebase_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datebase',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
